// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnxnvzweivyrxfwnvjwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ueG52endlaXZ5cnhmd252andpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDg2MTQsImV4cCI6MjA3MjIyNDYxNH0.j6jOFR3mrwFli-_3lnpykTf29H-hrcSI5_YWEt328qY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});